<a href="https://colab.research.google.com/github/Shirin1309/Python-files/blob/main/datascience_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

ar=np.array(my_matrix)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np
np.a=[1,2,3]
print(a+a)
print(np.a+np.a)


[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [ ]:
import numpy as np
np.arange(0,20,4)


array([ 0,  4,  8, 12, 16])

In [ ]:
np.zeros((2,2))
np.ones((2,2))
x=np.eye(3)
print(x.shape)




(3, 3)


In [ ]:
x1=np.max(x)
print(x1)

1.0


In [ ]:
x2=np.min(x)
print(x2)


0.0


In [ ]:
x3=np.argmax(x)
print(x3)

0


In [ ]:
#shape
arr=np.arange(0,25)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
d=np.full((5,5),7)
print(d)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
arr_sum=np.sum(d)
arr_sum

175

In [ ]:
#doing an operation on arow and a coloumn
a=[1,2,3]
b=[5,66,7]
c=[8,5,4]
myarr1=np.matrix([a,b,c])
print(myarr1)

[[ 1  2  3]
 [ 5 66  7]
 [ 8  5  4]]


In [ ]:
myarr1[2:6]

matrix([[8, 5, 4]])

In [ ]:
#broadcasting
myarr1[2:6]=199
myarr1

matrix([[  1,   2,   3],
        [  5,  66,   7],
        [199, 199, 199]])

In [ ]:
myarr1[:]=35
myarr1

matrix([[35, 35, 35],
        [35, 35, 35],
        [35, 35, 35]])

In [ ]:
a=myarr1.copy()
a


matrix([[35, 35, 35],
        [35, 35, 35],
        [35, 35, 35]])

In [ ]:
#indexing 2D array
x=np.arange(1,39)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38])

In [ ]:
np.linspace(2.0,3.0, num=5 )#to create sequence in python

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
#PANDAS
#extremely powerful version of excel, with a lot more features
#topics:- series,dataFrames,Missingdata,GroupBy,DataInput and Output


In [ ]:
#series:- 1 dimensional labeled array holding data of any type
import numpy as np
import pandas as pd
a=['a','b','c']
b=[1,2,3]
arr=np.array([1,2,3])
d={'a':1,'b':2,'c':3}
pd.Series(data=b,index=a)

a    1
b    2
c    3
dtype: int64

In [ ]:
pd.Series(arr) #only data

0    1
1    2
2    3
dtype: int64

In [ ]:
pd.Series(arr,a)

a    1
b    2
c    3
dtype: int64

In [ ]:
pd.Series(d)

a    1
b    2
c    3
dtype: int64

In [ ]:
pd.Series(data=a)

0    a
1    b
2    c
dtype: object

In [ ]:
#using an index

series1=pd.Series([1,2,3,4],index=['abc','efg','jkl','mnb'])
series2=pd.Series([1,2,3,4],index=['abc','ehhjg','jkl','mnb'])
series1+series2

abc      2.0
efg      NaN
ehhjg    NaN
jkl      6.0
mnb      8.0
dtype: float64

In [ ]:
from numpy.random import randn
randn(5,4)


array([[ 0.97264307, -0.036636  , -0.65982977, -0.07108114],
       [-0.33033587, -1.85336971,  1.22901593, -0.75626701],
       [ 2.58687955, -0.77071312,  1.79394776,  1.50302433],
       [-0.51426222,  1.01196811, -0.33529202,  0.12018448],
       [ 1.72405995,  0.28453354, -0.63722234, -0.2353442 ]])

In [ ]:
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','F','H','I','J'])
df

ValueError: ignored

In [ ]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A  1.041420 -1.477646 -0.426929 -1.346812
B  1.018855  0.116417  1.271718  1.264524
C -0.018040  0.074394 -0.803172 -0.830028
D -1.349614 -1.741530 -0.493035  1.306988
E -0.198333 -1.597407  1.586439 -2.002928

In [ ]:
df.reset_index()


index         W         X         Y         Z
0     A  1.041420 -1.477646 -0.426929 -1.346812
1     B  1.018855  0.116417  1.271718  1.264524
2     C -0.018040  0.074394 -0.803172 -0.830028
3     D -1.349614 -1.741530 -0.493035  1.306988
4     E -0.198333 -1.597407  1.586439 -2.002928

In [ ]:
df[df>0]

W         X         Y         Z
A  1.041420       NaN       NaN       NaN
B  1.018855  0.116417  1.271718  1.264524
C       NaN  0.074394       NaN       NaN
D       NaN       NaN       NaN  1.306988
E       NaN       NaN  1.586439       NaN

In [ ]:
df[df['W']>0]

W         X         Y         Z
A  1.041420 -1.477646 -0.426929 -1.346812
B  1.018855  0.116417  1.271718  1.264524

In [ ]:
#missing data
import numpy as np
import pandas as pd
mdata=

In [ ]:
mdata.dropna()
mdata.dropna(axis=1)#drop coloms having nan values
mdata.dropna(thresh=2)#drop rows having more than 2 nan values
mdata.fillna(value='Fill value')# nan value replaced by 'fill value'
mdata['A'].fillna(value=mdata['A'].mean())#fill with main values

In [ ]:
#CSV:-comma separated values
#for csv files
df=pd.read_csv('filename')
df.head()#print 1st 5 values of data file
df.tail()#last 5 values
df.head(12)#1st 12 values


In [ ]:
print(df.loc[[10,1],['mpg','cyl']])

In [ ]:
#excel
import xlrd #pip install xlrd
xx=pd.read_excel('filename.xlsx')

In [ ]:
#we can import html,json data etc
